### ISSUE TITLE
cannot put config file in different directory

### ISSUE THREAD

**Issue by GoogleCodeExporter** [24x-fi/pytox#16]
```
If I put the tox.ini config file in a directory other than PWD, tox fails 
strangely:

sridharr@whymac ~/as/project$ tox -c etc/tox/tox.ini
_______________________________________________________________________________ 
[tox sdist] 
_______________________________________________________________________________
[TOX] ***creating sdist package
Traceback (most recent call last):
  File "/Users/sridharr/Library/Python/2.7/bin/tox", line 9, in <module>
    load_entry_point('tox==0.9', 'console_scripts', 'tox')()
  File "/Users/sridharr/Library/Python/2.7/lib/python/site-packages/tox/_cmdline.py", line 19, in main
    retcode = Session(config).runcommand()
  File "/Users/sridharr/Library/Python/2.7/lib/python/site-packages/tox/_cmdline.py", line 121, in runcommand
    return self.subcommand_test()
  File "/Users/sridharr/Library/Python/2.7/lib/python/site-packages/tox/_cmdline.py", line 191, in subcommand_test
    sdist_path = self.sdist()
  File "/Users/sridharr/Library/Python/2.7/lib/python/site-packages/tox/_cmdline.py", line 177, in sdist
    sdist_path = self._makesdist()
  File "/Users/sridharr/Library/Python/2.7/lib/python/site-packages/tox/_cmdline.py", line 140, in _makesdist
    raise tox.exception.MissingFile(setup)
tox._exception.MissingFile: MissingFile: 
/Users/sridharr/as/project/etc/tox/setup.py

```

Original issue reported on code.google.com by `Sridhar....@gmail.com` on 8 Jan 2011 at 12:07

**Comment by GoogleCodeExporter** [comment]
```
Hmm, setupdir is by default set to the parent directory of the config file:

        config.setupdir = reader.getpath(toxsection, "setupdir", "{toxinidir}")

In my project, I have more than one tox config file ... so, to keep the 
toplevel directory clean, I put them under etc/tox.
```

Original comment by `Sridhar....@gmail.com` on 8 Jan 2011 at 12:12

**Comment by GoogleCodeExporter** [comment]
```
A workaround is to add `setupdir = ../..` (not sure if this will work on 
Windows)

```

Original comment by `Sridhar....@gmail.com` on 8 Jan 2011 at 12:20
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately, this causes problems due to CWD being etc/tox. For example, I 
got this error:

platform darwin -- Python 2.7.1 -- pytest-2.0.0 -- 
/Users/sridharr/as/pypm/etc/tox/.tox/py27/bin/python
ERROR: file not found: src/pypm/test

This is  because of the following command line used in tox.ini:

  commands = py.test -x -v src/pypm/test --junitxml=tmp/testreport.xml

tox is running the command from etc/tox, instead of the actual working 
directory.  Should I add ../.. to these commands as well? What is the best way?
```

Original comment by `Sridhar....@gmail.com` on 8 Jan 2011 at 12:39

**Comment by GoogleCodeExporter** [comment]
```
i think having setupdir default to CWD (even if toxinidir is custom) would help 
 your situation. Otherwise you'd probably need to use a "changedir" setting 
which is a bit awkward.  Basically 

   config.setupdir = reader.getpath(toxsection, "setupdir", py.path.local())

should implement the suggestion.  If you agree, it'd be cool if you can add a 
test to test_config.py and a changelog entry and commit. 


```

Original comment by `holger.k...@gmail.com` on 11 Jan 2011 at 3:27
